n1=int(input("primer numerador="))
d1=int(input("primer denominador="))
n2=int(input("segundo numerador="))
d2=int(input("segundo denominador="))
print(n1,"/",d1,",",n2,"/",d2)
s=float(n1/d1+n2/d2)
r=float(n1/d1-n2/d2)
m=float((n1/d1)*(n2/d2))
d=float((n1/d1)/(n2/d2))
print("la suma es igual a:",s)
print("la resta es igual a:",r)
print("la multiplicacion es igual a:",m)
print("la division es igual a:",d)